### ISSUE TITLE
Code open source?

### ISSUE THREAD

**Issue by Razer6** [azonenberg/antikernel#1]
Is the code for Antikernel's architecture already open source?

**Comment by azonenberg** [comment]
Good news: It's open source. There's a public SVN browser at http://redmine.drawersteak.com/projects/achd-soc/repository/show/trunk. That code is under the same 3-clause BSD license as this Github repository.

Bad news: The build system for the current codebase is a giant pain in the neck full of hard-coded paths to shell scripts etc, so it's unlikely that anyone but me will ever be able to compile it (without a total rewrite of all the build scripts, at least). I was too busy trying to graduate to make something nice, sorry :)

I'm in the process of re-writing the build system from scratch here https://github.com/azonenberg/splash-build-system to be much cleaner and simpler. Once that's taken care of, I'll be migrating the old SVN code here. Current estimate is another 1-2 months of work, end of the year worst case.

If you have further questions post them in this thread. I'll keep the issue open until the code is actually migrated to this repo.
